# Generated by Django 2.1.5 on 2020-09-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('reference', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your full name', max_length=100, null=True)),
                ('login', models.CharField(help_text='Enter your company email id', max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'JAN'), ('02', 'FEB'), ('03', 'MAR'), ('04', 'APR'), ('05', 'MAY'), ('06', 'JUN'), ('07', 'JUL'), ('08', 'AUG'), ('09', 'SEP'), ('10', 'OCT'), ('11', 'NOV'), ('12', 'DEC')], max_length=2)),
                ('year', models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], max_length=4)),
                ('submitting_date', models.DateTimeField(auto_now_add=True)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('week1', models.DecimalField(decimal_places=2, max_digits=2)),
                ('week2', models.DecimalField(decimal_places=2, max_digits=2)),
                ('week3', models.DecimalField(decimal_places=2, max_digits=2)),
                ('week4', models.DecimalField(decimal_places=2, max_digits=2)),
                ('reference_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Employee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hours',
            unique_together={('month', 'year')},
        ),
    ]
