# Generated by Django 2.1.5 on 2020-09-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('reference', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Enter your full name', max_length=100, null=True)),
                ('login', models.EmailField(help_text='Enter your company email id', max_length=200, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
