# Generated by Django 2.1.5 on 2020-09-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
