# Generated by Django 2.1.5 on 2020-09-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hours',
            unique_together={('month', 'year')},
        ),
    ]
