# Generated by Django 2.1.5 on 2020-09-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0002_auto_20200923_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='week1',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hours',
            name='week2',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hours',
            name='week3',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hours',
            name='week4',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
