# Generated by Django 2.1.5 on 2020-09-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0003_auto_20200923_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='status',
            field=models.CharField(choices=[('YET TO SUBMIT', 'YET TO SUBMIT'), ('SUBMITTED', 'SUBMITTED'), ('COMPLETED', 'COMPLETED')], default='YET TO SUBMIT', max_length=20),
        ),
    ]
