# Generated by Django 2.1.5 on 2020-09-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0005_auto_20200924_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='hours',
            unique_together=set(),
        ),
    ]
