# Generated by Django 2.1.5 on 2020-09-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0006_auto_20200929_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='year',
            field=models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='2020', max_length=4),
        ),
    ]
